# Generated by Django 4.2.3 on 2023-07-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
